KEY_ACTION = "action"
KEY_PROPERTY = "property"
KEY_ENDPOINT = "endpoint"

ACTION_ONOFF = "onoff"
ACTION_LEVEL = "level"
ACTION_CW = "cw"
ACTION_HSV = "hsv"
ACTION_POSITION = "position"
ACTION_SENSOR = "sensor"
ACTION_KEY = "key"
ACTION_ENERGY = "energy"
ACTION_TOTAL_ENERGY = "total_energy"

PROP_ONOFF = "onoff"
PROP_LEVEL = "level"
PROP_H = "h"
PROP_S = "s"
PROP_V = "v"
PROP_CW = "cw"
PROP_POSITION = "position"
PROP_LIGHT_INTENSITY = "lightIntensity"
PROP_PIR_TRIGGER = "pirTrigger"
PROP_KEY_EVENT = "key_event"
PROP_POWER = "power"
PROP_TOTAL_ENERGY = "total_energy"
